#+ summary: "Retrieve a specific Observation"
#+ description: "NOTE: make sure response content type is application/json"
#+ endpoint: "https://www.foodie-cloud.org/sparql?default-graph-uri=http://w3id.org/iliad/dataaset/jf-pilot-sample"
#+ tags: [ "test" ]
#+ method: "GET"
#+ pagination: 100
#+ transform: {
#+   "@iot.id": "?s",
#+   "$anchor": "@iot.id",
#+   "resultTime": "?resultTime",
#+   "otro": "?otroInfo",
#+ }

PREFIX iliad-api: <https://w3id.org/iliad/api>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX oim-jf:  <http://w3id.org/iliad/oim/jellyfish#> 
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX bif: <bif:>

SELECT DISTINCT ?s ?resultTime ?otroInfo
WHERE {
    ?s a sosa:Observation ;
        		sosa:resultTime ?resultTime ;
            sosa:phenomenonTime ?phenomenonTime ;
            sosa:hasResult ?result .
    ?result oim-jf:densityOfJF ?densityOfJF ;
            dwc:sampleSizeValue ?sampleSizeValue ;
            dwc:scientificName ?scientificName ;
            oim-jf:wormsConcept ?wormsConcept .
   OPTIONAL { ?s ?p ?_page } 
   BIND (URI(CONCAT('https://w3id.org/iliad/api/v1.0/Observations?$top=100&$skip=', xsd:integer(?_page)*100)) AS ?otroInfo)
   # works    FILTER (strEnds(STR(?s), CONCAT('/',?_otro)))
## works     FILTER (contains(STR(?resultTime), ?_page))
}



